name: Publish UPM Package

# manually trigger the workflow
on: [push]

jobs:
  upm-update-and-publish:
    env:      
      REGISTRY_NAME: ghcr.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2          
    - name: Find UPM package.json & increment its version number
      uses: mempic/UnityUPMSemver@main
      id: semver-update-upm
      with:
        semver-update-type: 'patch'
        upm-package-directory: ''
