name: Publish UPM Package

# manually trigger the workflow
on: workflow_dispatch

jobs:
  upm-release-essential:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: paulhatch/semantic-version@v4.0.2
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "0.0.${increment}"
        change_path: "src/my-service"
        namespace: project-b
        short_tags: true
        bump_each_commit: false
    - uses: quabug/create-upm-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upm_package_path: ./
        upm_tag_prefix: build/
