name: Publish UPM Package

# manually trigger the workflow
on: workflow_dispatch

jobs:
  upm-update-and-publish:
    env:      
      REGISTRY_NAME: ghcr.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: remorses/bump-version@js
      with:
          version_file: ./package.json
          prerelease_tag: test
          github_token: ${{ secrets.GITHUB_TOKEN }}          
          ignore: dist, ignored_folder
#     - name: Find UPM package.json & increment its version number
#       uses: AlexHolderDeveloper/UnityUPMSemver@v0.0.1 # Change vX.X.X to whatever tag is newer in the AlexHolderDeveloper/UnityUPMSemver repository.
#       id: semver-update-upm
#       with:
#         semver-update-type: 'patch'
#         upm-package-directory: ''
          
    - uses: monry/actions-upm-publish@v1
      with:
        npm_registry_url: ${{ env.REGISTRY_NAME }}
        npm_auth_token: ${{ secrets.GITHUB_TOKEN }}
        package_directory_path: ''

#     - uses: quabug/create-upm-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       with:
#         upm_package_path: ./
#         upm_tag_prefix: build/
