# name: Publish UPM Package

# # manually trigger the workflow
# on: workflow_dispatch

# jobs:
#   upm-update-and-publish:
#     env:      
#       REGISTRY_NAME: ghcr.io
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - uses: remorses/bump-version@js
#       with:
#           version_file: ./package.json
#           prerelease_tag: test
#           github_token: ${{ secrets.GITHUB_TOKEN }}          
#           ignore: dist, ignored_folder
          
#     - name: Find UPM package.json & increment its version number
#       uses: mempic/UnityUPMSemver@main
#       id: semver-update-upm
#       with:
#         semver-update-type: 'patch'
#         upm-package-directory: ''

name: Update Unity project semantic versioning

on: [push]

jobs:
    create:
        name: Update semver
        runs-on: ubuntu-latest
    
        steps:
            # You must ALWAYS checkout your repo so that actions in the workflow can use it.
        - name: Checkout 
          uses: actions/checkout@v2

        - name: Find ProjectSettings.asset & increment its bundleVersion number
          uses: mempic/UnityUPMSemver@main # Change v1.0.0 to whatever tag is newer in the AlexHolderDeveloper/UnityAutomatedSemver repository.
          id: semver-update
          with:            
            semver-update-type: 'patch' # Change this string to any suitable string mentioned in the Inputs section of this action's readme to suit your needs.
            upm-package-directory: ''
            # Validate that the number has been incremented correctly.
        - name: Get the new semver number
          run: echo "The new semver number for this Unity project is ${{ steps.semver-update.outputs.semver-number }}"

            # Commit & push the updated semver number back into the repo. Yes, you have to fetch & pull in your local workstation after this step is done.
        - name: Push changed files back to repo
          uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Updated semver via automated action."
            commit_options: '--no-verify --signoff'
          
        - uses: actions/checkout@v2

        - name: Set current date as env variable 
          id: date
          run: echo "::set-output name=date::$(date +'%Y%m%d')" 

        - name: Make sure we have an output directory for the legacy package
          run: mkdir legacyPackage

        - name: Push package directory to subtree
          uses: s0/git-publish-subdir-action@develop
          env:
            REPO: self
            BRANCH: upm 
            FOLDER: Assets/BigfootDS/BigfootUnityUtilities/
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Build legacy Unity package
          run: |
            echo "Assets/BigfootDS/BigfootUnityUtilities/Runtime.meta" > metaList
            find Assets/BigfootDS/BigfootUnityUtilities/Runtime/ -name \*.meta >> metaList
  
        - uses: pCYSl5EDgo/create-unitypackage@master
          with:
            package-path: 'legacyPackage/${{ github.event.repository.name }}_${{ steps.date.outputs.date }}_${{ github.run_number }}.unitypackage'
            include-files: metaList

        - name: Upload legacy Unity package to repository Releases section
          uses: actions/upload-artifact@master
          with:
            path: legacyPackage
            name: ${{ github.event.repository.name }}_${{ steps.date.outputs.date }}_${{ github.run_number }}Package
    
        - name: Create release
          uses: fnkr/github-action-ghr@v1
          if: startsWith(github.ref, 'refs/tags/')
          env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            GHR_PATH: legacyPackage
            # GHR_COMPRESS: zip
