name: Publish UPM Package

# manually trigger the workflow
on: [push]

jobs:
  upm-update-and-publish:
    env:      
      REGISTRY_NAME: ghcr.io
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
#     - uses: remorses/bump-version@js
#       with:
#           version_file: ./package.json
#           prerelease_tag: test
#           github_token: ${{ secrets.GITHUB_TOKEN }}          
#           ignore: dist, ignored_folder
          
    - name: Find UPM package.json & increment its version number
      uses: mempic/UnityUPMSemver@main
      id: semver-update-upm
      with:
        semver-update-type: 'patch'
        upm-package-directory: ''
